Add-PSSnapIn Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

$dir = "C:\CMB\FileToUpload\"
$latest = Get-ChildItem -Path $dir | Sort-Object LastAccessTime -Descending | Select-Object -First 1
$latest.name

$strPath = $dir + $latest.name

$objExcel = New-Object -Com "Excel.Application"
$objExcel2 = New-Object -Com "Excel.Application"
$objExcel.Visible = $false
$objExcel.DisplayAlerts = $false
$objExcel2.Visible = $false
$objExcel2.DisplayAlerts = $false

$WorkBook = $objExcel.Workbooks.Open($strPath)
$WorkBook2 = $objExcel2.Workbooks.Add()
$worksheet = $workbook.Sheets.Item(1)

$intRowMax =  ($worksheet.UsedRange.Rows).count

$FormulaRange = $worksheet.range("A18:BT$intRowMax")
$FormulaRange.Copy()
$Worksheet2 = $WorkBook2.Sheets.Item(1)
$Worksheet2.Paste()
$WorkBook2.SaveAs("C:\CMB\FileToUpload\AUTOGENERATED.csv", 6)
$objExcel.Quit()
$objExcel2.Quit()
 
#$webURL = “http://cmbdemo.canadacentral.cloudapp.azure.com/sites/Dev”
$webURL = "http://uat.collaboration.mbgov.ca/sites/cmb/mesV1.1"
$web = Get-SPWeb -Identity $webURL
#$listName = "CMBimport"
$listName = "StageOneImport"
$list= $web.Lists["$listName"]

$header = "Invoice Name","Agency","Invoice Line #","Agency Child ID","Child Last Name","Child First name","Child Date of Birth","Age Category","Legal Status","Jurisdiction","Gender","Treaty #","Placement Type","Placement Name","Agency Placement ID","Placement Address","Placement Community","Postal Code (of Placement Address)","Month of Service","Year of Service","Start Day (in month billed)","End Day (in month billed)","Billable Days","Rate Code","Level of Care","For Future Use","All Inclusive Placement Per Diem","Basic Rate per diem","Agency Allowance per diem","Northern Food per diem","Shelter per diem","Total Basic Per Diem","Fee for Service Per Diem","Total Basic for Month","Fee for Service for Month","Total All Inclusive Rate for Month","Total Special Needs","Total Billed","Support Worker paid to Foster Parent","Support Worker paid direct","Day Care","Respite paid to Foster Parent","Respite paid direct","Initial Child Assessment (only paid once per child)","Court Ordered Assessment (needs to be verified with Ben)","Elder Services","Therapy","Initial Clothing","Emergency Placement Costs","External Agency Admin Fees","Home Visit","Reunification","Prescriptions","Dental","Orthodontics","Optical","General Medical","Medical Transportation","Transportation","Legal","Criminal Legal","Child ID (birth certificate, passport)",'Car Seats up to $200.00','Cribs up to $400.00',"Camp","Retain Bed Space","Funeral / Bereavement","Age of Majority","Other Special Needs","Exceptional Circumstance One Time Cost","Independent Living Costs","Other Special Needs Code/Description"
$WorkBook3 = import-csv "C:\CMB\FileToUpload\AUTOGENERATED.csv" -Header $header

$intRow = 1
 
foreach ($CSVitem in $WorkBook3)
{
    $item = $list.Items.Add();
    $item["InvoiceName"] = $CSVitem."Invoice Name"
    $item["Agency"] = $CSVitem."Agency"
    $item["Invoice Line #"] = $CSVitem."Invoice Line #"
    $item["Agency Child ID"] = $CSVitem."Agency Child ID"
    $item["Child Last Name"] = $CSVitem."Child Last Name"
    $item["Child First name"] = $CSVitem."Child First name"
    $item["Child Date of Birth"] = [datetime]$CSVitem."Child Date of Birth"
    $item["Age Category"] = $CSVitem."Age Category"
    $item["Legal Status"] = $CSVitem."Legal Status"
    $item["Jurisdiction"] = $CSVitem."Jurisdiction"
    $item["Gender"] = $CSVitem."Gender"
    $item["Treaty #"] = $CSVitem."Treaty #"
    $item["Placement Type "] = $CSVitem."Placement Type"
    $item["Placement Name"] = $CSVitem."Placement Name"
    $item["Agency Placement ID"] = $CSVitem."Agency Placement ID"
    $item["Placement Address"] = $CSVitem."Placement Address"
    $item["Placement Community"] = $CSVitem."Placement Community"
    $item["Postal Code (of Placement Address)"] = $CSVitem."Postal Code (of Placement Address)"
    $item["Month of Service"] = $CSVitem."Month of Service"
    $item["Year of Service"] = $CSVitem."Year of Service"
    $item["Start Day (in month billed)"] = $CSVitem."Start Day (in month billed)"
    $item["End Day (in month billed)"] = $CSVitem."End Day (in month billed)"
    $item["Billable Days"] = $CSVitem."Billable Days"
    $item["Rate Code "] = $CSVitem."Rate Code"
    $item["Level of Care"] = $CSVitem."Level of Care"
    $item["For Future Use"] = $CSVitem."For Future Use"
    $item["All Inclusive Placement Per Diem"] = $CSVitem."All Inclusive Placement Per Diem"
    $item["Basic Rate per diem"] = $CSVitem."Basic Rate per diem"
    $item["Agency Allowance per diem"] = $CSVitem."Agency Allowance per diem".Replace("$-",0)
    $item["Northern Food per diem"] = $CSVitem."Northern Food per diem".Replace("$-",0)
    $item["Shelter per diem"] = $CSVitem."Shelter per diem".Replace("$-",0)
    $item["Total Basic Per Diem"] = $CSVitem."Total Basic Per Diem".Replace("$-",0)
    $item["Fee for Service Per Diem"] = $CSVitem."Fee for Service Per Diem".Replace("$-",0)
    $item["Total Basic for Month"] = $CSVitem."Total Basic for Month".Replace("$-",0)
    $item["Fee for Service for Month"] = $CSVitem."Fee for Service for Month".Replace("$-",0)
    $item["Total All Inclusive Rate for Month"] = $CSVitem."Total All Inclusive Rate for Month".Replace("$-",0)
    $item["Total Special Needs"] = $CSVitem."Total Special Needs".Replace("$-",0)
    $item["Total Billed"] = $CSVitem."Total Billed".Replace("$-",0)
    $item["Support Worker paid to Foster Parent"] = $CSVitem."Support Worker paid to Foster Parent".Replace("$-",0)
    $item["Support Worker paid direct"] = $CSVitem."Support Worker paid direct".Replace("$-",0)
    $item["Day Care"] = $CSVitem."Day Care".Replace("$-",0)
    $item["Respite paid to Foster Parent"] = $CSVitem."Respite paid to Foster Parent".Replace("$-",0)
    $item["Respite paid direct"] = $CSVitem."Respite paid direct".Replace("$-",0)
    $item["Initial Child Assessment"] = $CSVitem."Initial Child Assessment (only paid once per child)".Replace("$-",0)
    $item["Court Ordered Assessment"] = $CSVitem."Court Ordered Assessment (needs to be verified with Ben)".Replace("$-",0)
    $item["Elder Services"] = $CSVitem."Elder Services".Replace("$-",0)
    $item["Therapy"] = $CSVitem."Therapy".Replace("$-",0)
    $item["Initial Clothing"] = $CSVitem."Initial Clothing".Replace("$-",0)
    $item["Emergency Placement Costs"] = $CSVitem."Emergency Placement Costs".Replace("$-",0)
    $item["External Agency Admin Fees"] = $CSVitem."External Agency Admin Fees".Replace("$-",0)
    $item["Home Visit"] = $CSVitem."Home Visit".Replace("$-",0)
    $item["Reunification"] = $CSVitem."Reunification".Replace("$-",0)
    $item["Prescriptions"] = $CSVitem."Prescriptions".Replace("$-",0)
    $item["Dental"] = $CSVitem."Dental".Replace("$-",0)
    $item["Orthodontics"] = $CSVitem."Orthodontics".Replace("$-",0)
    $item["Optical"] = $CSVitem."Optical".Replace("$-",0)
    $item["General Medical"] = $CSVitem."General Medical".Replace("$-",0)
    $item["Medical Transportation"] = $CSVitem."Medical Transportation".Replace("$-",0)
    $item["Transportation"] = $CSVitem."Transportation".Replace("$-",0)
    $item["Legal"] = $CSVitem."Legal".Replace("$-",0)
    $item["Criminal Legal"] = $CSVitem."Criminal Legal".Replace("$-",0)
    $item["Child ID (birth certificate, passport)"] = $CSVitem."Child ID (birth certificate, passport)".Replace("$-",0)
    $item['Car Seats up to $200.00'] = $CSVitem.'Car Seats up to $200.00'.Replace("$-",0)
    $item['Cribs up to $400.00'] = $CSVitem.'Cribs up to $400.00'.Replace("$-",0)
    $item["Camp"] = $CSVitem."Camp".Replace("$-",0)
    $item["Retain Bed Space"] = $CSVitem."Retain Bed Space".Replace("$-",0)
    $item["Funeral / Bereavement"] = $CSVitem."Funeral / Bereavement".Replace("$-",0)
    $item["Age of Majority"] = $CSVitem."Age of Majority".Replace("$-",0)
    $item["Other Special Needs"] = $CSVitem."Other Special Needs".Replace("$-",0)
    $item["Exceptional Circumstance One Time Cost"] = $CSVitem."Exceptional Circumstance One Time Cost".Replace("$-",0)
    $item["Independent Living Costs"] = $CSVitem."Independent Living Costs".Replace("$-",0)
    $item["Other Special Needs Code/Description"] = $CSVitem."Other Special Needs Code/Description".Replace("$-",0)
    
    Write-Host $intRow

    $item.Update()
    $intRow++
}
 
$web.Dispose()
Remove-Item "C:\CMB\FileToUpload\AUTOGENERATED.csv"